# Configure build behavior for cross-compilation
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-C", "link-arg=-s"]

# Use the "line-tables-only" debug info format which tends to have fewer file locking issues
[profile.dev.package."*"]
debug = "line-tables-only" 

[build]
# Limit parallel jobs to reduce chance of access conflicts
jobs = 2
